url: "https://reikisaltlakecity.com"
title: Reiki Light Salt Lake City
phone: (385) 483-2264
logo: reiki-light-logo-white.png
logo_alt: reiki-light-logo.png
logo-width: 200

google-analytics: G-RMWJRLXR4C
site-author: 325 Studio

category-list: [training, healing]

# Fonts
font:
  # Body copy
  sans-serif-name: 'Open Sans'
  sans-serif: "https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;700&display=swap" 
  # Heading copy
  serif-name: 'Playfair Display'
  serif: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;700&display=swap"

# Privacy Policy and Terms of Service page
state: Utah

# Custom Navbar Colors
navbar-colors:
  bg: "#7C59C7"
  menu-color: "rgba(255, 255, 255, 0.8)"
  active-color: "rgba(255, 255, 255, 0.8)" # Set to the same as menu-color for now.
  menu-hover-color: "rgba(255, 255, 255, 1.0)"

# Custom button
btn-custom-primary:
  text-color: "#ffffff"
  bg: "#7C59C7"
  border-color: "#7C59C7"
  hover-text-color: "#ffffff"
  hover-bg: "#7C59C7"
  hover-border-color: "#7C59C7"

btn-custom-secondary:
  text-color: "#000000"
  bg: "#ffffff"
  border-color: "#ffffff"
  hover-text-color: "#000000"
  hover-bg: "#e4e9ed"
  hover-border-color: "#000000"

btn-border-radius: "8px"

# Call to action box bg color
cta:
  bg: "#7C59C7"
  
# Form background color
form: 
  bg: "#DFD8F2"


# Local Business Schema
schema:
  # name: Same as title above
  type: LocalBusiness
  image: 
  # telephone: Same as phone above
  priceRange: "$"
  address:
    city: "Salt Lake City"
    state: "Utah"
    country: "USA"
    postalCode: "84101"
  hours:
    dayOfWeek: "Mondayâ€“Saturday"
  # url: Same as url above
# End Schema